server:
  port: 8110
spring:
  devtools.add-properties: false
  jpa: 
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/waltz 
    password: waltz  
    username: waltz
springdoc:
  swagger-ui.path: /swagger-ui
  api-docs.path: /api-docs
  show-actuator: true
logging:
  level:
    web: INFO
