# Server Configuration
server:
  port: 1020

debug: true

spring:
  application:
    name: silo
  sql:
    init:
      mode: never

  # MailSender Configuration
  mail:
    host: smtp.google.com
    port: 587
    username: youremail@gmail.com
    password: your-app-password-from-previous-step (Without spaces or any special character)
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
        mime:
          charset: UTF

  # Datasource Configuration
  datasource:
    # driver-class-name:
    url: jdbc:postgresql://localhost:5432/siloDb
    username: siloUser
    password: 0P0lacam!

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ddl-auto  
    properties:
      hibernate:
        boot:
          # allow_jdbc_metadata_access: false
  
  # Security Configuration
  security:
    oauth2:
      client:
        registration: 
          google: 
            client-id: 247464265015-astrh9vll11l22scpds7rdn6q8b8bbo7.apps.googleusercontent.com
            client-secret: RZptmh1c6LEfNhYHDLqGLqAJ
            scope: email,profile
          github: 
            client-id: 95162f0ca4fbb8236c3d
            client-secret: c80297b73b6710455005bd5cfd4427fe7034b9ed
            scope: email,read:user     
          facebook: 
            client-id: 4453217618039998
            client-secret: 8b3ef3edaec63d2905c50decd3db471e
            scope: email,public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            user-info-uri: https://graph.facebook.com/v10.0/me?fields=email,first_name,last_name,name

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
        
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
    filter: false
    syntaxHighlight:
      activated: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

# Custom Configuration

hostname: localhost:3000
mail.debug: false
recaptcha:
  secret: 6Lc5cLkZAAAAANUjd4--Jx6PioSC_N-9MFKT3PsA
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

jwt: 
  header: Authorization
  secret: dejavu
  expiration: 604800

structurizr:
  client:
    endpoint:
    key:
    secret: