# Server Configuration
server:
  port: 3000
debug: true

spring:
  application:
    name: silo

  # Datasource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5434/siloDb
    username: siloUser
    password: 0P0lacam!
    hikari:
      connection-timeout: 20000
      maximum-pool-size:  5

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase configuration
  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog-master.yaml

  # MailSender Configuration
  mail:
    host: smtp.google.com
    port: 587
    username: youremail@gmail.com
    password: 0P0lacam!
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
        mime:
          charset: UTF

  # Security Configuration
  security:
    jwt:
      secret-key: dejavu
      expiration: 604800
    oauth2:
      client:
        registration: 
          google: 
            client-id: 247464265015-astrh9vll11l22scpds7rdn6q8b8bbo7.apps.googleusercontent.com
            client-secret: RZptmh1c6LEfNhYHDLqGLqAJ
            scope: email,profile
          github: 
            client-id: 95162f0ca4fbb8236c3d
            client-secret: c80297b73b6710455005bd5cfd4427fe7034b9ed
            scope: email,read:user     
          facebook: 
            client-id: 4453217618039998
            client-secret: 8b3ef3edaec63d2905c50decd3db471e
            scope: email,public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            user-info-uri: https://graph.facebook.com/v10.0/me?fields=email,first_name,last_name,name

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
        
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
    filter: false
    syntaxHighlight:
      activated: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

# Custom Configuration
hostname: localhost:3000
mail.debug: false
recaptcha:
  secret: 6Lc5cLkZAAAAANUjd4--Jx6PioSC_N-9MFKT3PsA
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

jwt: 
  header: Authorization
  secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
  expiration: 604800

structurizr:
  client:
    endpoint:
    key:
    secret:

main.liquibase.change-log: classpath:database/db.changelog-master.yaml