version: "3.8"

services:
  langflow:
    image: dobraalkan/silo:1.0-alpha
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://siloUser:0P0lacam!@localhost:5432/siloDb
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/silo
    volumes:
      - silo-data:/app/silo

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: siloUser
      POSTGRES_PASSWORD: 0P0lacam!
      POSTGRES_DB: siloDb
    ports:
      - "5432:5432"
    volumes:
      - silo-postgres:/var/lib/postgresql/data

volumes:
  silo-postgres:
  silo-data:
