/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.records;


import com.silo.backend.database.tables.ApplicationGroupOuEntry;
import com.silo.backend.database.tables.interfaces.IApplicationGroupOuEntry;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * app groups can include reference to org units. Apps associated to the org
 * unit are included in the group at runtime
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "application_group_ou_entry"
)
public class ApplicationGroupOuEntryRecord extends TableRecordImpl<ApplicationGroupOuEntryRecord> implements IApplicationGroupOuEntry {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>application_group_ou_entry.group_id</code>. reference to
     * the group this entry belongs to
     */
    public ApplicationGroupOuEntryRecord setGroupId(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>application_group_ou_entry.group_id</code>. reference to
     * the group this entry belongs to
     */
    @Column(name = "group_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getGroupId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>application_group_ou_entry.org_unit_id</code>. reference
     * to the org unit this entry belongs to
     */
    public ApplicationGroupOuEntryRecord setOrgUnitId(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>application_group_ou_entry.org_unit_id</code>. reference
     * to the org unit this entry belongs to
     */
    @Column(name = "org_unit_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getOrgUnitId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>application_group_ou_entry.is_readonly</code>. flag to
     * indicate that the value is readonly.  Typically set if group entries are
     * added by external jobs
     */
    public ApplicationGroupOuEntryRecord setIsReadonly(@Nullable Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>application_group_ou_entry.is_readonly</code>. flag to
     * indicate that the value is readonly.  Typically set if group entries are
     * added by external jobs
     */
    @Column(name = "is_readonly")
    @Nullable
    @Override
    public Boolean getIsReadonly() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>application_group_ou_entry.provenance</code>. indicates
     * where this record originated. Will be 'waltz' if created via the UI
     */
    public ApplicationGroupOuEntryRecord setProvenance(@Nullable String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>application_group_ou_entry.provenance</code>. indicates
     * where this record originated. Will be 'waltz' if created via the UI
     */
    @Column(name = "provenance", length = 64)
    @Size(max = 64)
    @Nullable
    @Override
    public String getProvenance() {
        return (String) get(3);
    }

    /**
     * Setter for <code>application_group_ou_entry.created_at</code>. the date
     * this entry was created
     */
    public ApplicationGroupOuEntryRecord setCreatedAt(@Nullable Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>application_group_ou_entry.created_at</code>. the date
     * this entry was created
     */
    @Column(name = "created_at", precision = 6)
    @Nullable
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IApplicationGroupOuEntry from) {
        setGroupId(from.getGroupId());
        setOrgUnitId(from.getOrgUnitId());
        setIsReadonly(from.getIsReadonly());
        setProvenance(from.getProvenance());
        setCreatedAt(from.getCreatedAt());
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationGroupOuEntryRecord
     */
    public ApplicationGroupOuEntryRecord() {
        super(ApplicationGroupOuEntry.APPLICATION_GROUP_OU_ENTRY);
    }

    /**
     * Create a detached, initialised ApplicationGroupOuEntryRecord
     */
    @ConstructorProperties({ "groupId", "orgUnitId", "isReadonly", "provenance", "createdAt" })
    public ApplicationGroupOuEntryRecord(@Nonnull Long groupId, @Nonnull Long orgUnitId, @Nullable Boolean isReadonly, @Nullable String provenance, @Nullable Timestamp createdAt) {
        super(ApplicationGroupOuEntry.APPLICATION_GROUP_OU_ENTRY);

        setGroupId(groupId);
        setOrgUnitId(orgUnitId);
        setIsReadonly(isReadonly);
        setProvenance(provenance);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ApplicationGroupOuEntryRecord
     */
    public ApplicationGroupOuEntryRecord(com.silo.backend.database.tables.pojos.ApplicationGroupOuEntry value) {
        super(ApplicationGroupOuEntry.APPLICATION_GROUP_OU_ENTRY);

        if (value != null) {
            setGroupId(value.groupId());
            setOrgUnitId(value.orgUnitId());
            setIsReadonly(value.isReadonly());
            setProvenance(value.provenance());
            setCreatedAt(value.createdAt());
            resetChangedOnNotNull();
        }
    }
}
