/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.records;


import com.silo.backend.database.tables.CustomEnvironment;
import com.silo.backend.database.tables.interfaces.ICustomEnvironment;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "custom_environment"
)
public class CustomEnvironmentRecord extends TableRecordImpl<CustomEnvironmentRecord> implements ICustomEnvironment {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>custom_environment.id</code>.
     */
    public CustomEnvironmentRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.id</code>.
     */
    @Column(name = "id")
    @Nullable
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>custom_environment.owning_entity_id</code>.
     */
    public CustomEnvironmentRecord setOwningEntityId(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.owning_entity_id</code>.
     */
    @Column(name = "owning_entity_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getOwningEntityId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>custom_environment.owning_entity_kind</code>.
     */
    public CustomEnvironmentRecord setOwningEntityKind(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.owning_entity_kind</code>.
     */
    @Column(name = "owning_entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    @Override
    public String getOwningEntityKind() {
        return (String) get(2);
    }

    /**
     * Setter for <code>custom_environment.name</code>.
     */
    public CustomEnvironmentRecord setName(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.name</code>.
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>custom_environment.description</code>.
     */
    public CustomEnvironmentRecord setDescription(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.description</code>.
     */
    @Column(name = "description", length = 4000)
    @Size(max = 4000)
    @Nullable
    @Override
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>custom_environment.external_id</code>.
     */
    public CustomEnvironmentRecord setExternalId(@Nonnull String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.external_id</code>.
     */
    @Column(name = "external_id", nullable = false, length = 200)
    @NotNull
    @Size(max = 200)
    @Nonnull
    @Override
    public String getExternalId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>custom_environment.group_name</code>.
     */
    public CustomEnvironmentRecord setGroupName(@Nullable String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment.group_name</code>.
     */
    @Column(name = "group_name", length = 255)
    @Size(max = 255)
    @Nullable
    @Override
    public String getGroupName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(ICustomEnvironment from) {
        setId(from.getId());
        setOwningEntityId(from.getOwningEntityId());
        setOwningEntityKind(from.getOwningEntityKind());
        setName(from.getName());
        setDescription(from.getDescription());
        setExternalId(from.getExternalId());
        setGroupName(from.getGroupName());
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomEnvironmentRecord
     */
    public CustomEnvironmentRecord() {
        super(CustomEnvironment.CUSTOM_ENVIRONMENT);
    }

    /**
     * Create a detached, initialised CustomEnvironmentRecord
     */
    @ConstructorProperties({ "id", "owningEntityId", "owningEntityKind", "name", "description", "externalId", "groupName" })
    public CustomEnvironmentRecord(@Nullable Long id, @Nonnull Long owningEntityId, @Nonnull String owningEntityKind, @Nonnull String name, @Nullable String description, @Nonnull String externalId, @Nullable String groupName) {
        super(CustomEnvironment.CUSTOM_ENVIRONMENT);

        setId(id);
        setOwningEntityId(owningEntityId);
        setOwningEntityKind(owningEntityKind);
        setName(name);
        setDescription(description);
        setExternalId(externalId);
        setGroupName(groupName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomEnvironmentRecord
     */
    public CustomEnvironmentRecord(com.silo.backend.database.tables.pojos.CustomEnvironment value) {
        super(CustomEnvironment.CUSTOM_ENVIRONMENT);

        if (value != null) {
            setId(value.id());
            setOwningEntityId(value.owningEntityId());
            setOwningEntityKind(value.owningEntityKind());
            setName(value.name());
            setDescription(value.description());
            setExternalId(value.externalId());
            setGroupName(value.groupName());
            resetChangedOnNotNull();
        }
    }
}
