/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.records;


import com.silo.backend.database.tables.CustomEnvironmentUsage;
import com.silo.backend.database.tables.interfaces.ICustomEnvironmentUsage;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "custom_environment_usage"
)
public class CustomEnvironmentUsageRecord extends TableRecordImpl<CustomEnvironmentUsageRecord> implements ICustomEnvironmentUsage {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>custom_environment_usage.id</code>.
     */
    public CustomEnvironmentUsageRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.id</code>.
     */
    @Column(name = "id")
    @Nullable
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>custom_environment_usage.custom_environment_id</code>.
     */
    public CustomEnvironmentUsageRecord setCustomEnvironmentId(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.custom_environment_id</code>.
     */
    @Column(name = "custom_environment_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getCustomEnvironmentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>custom_environment_usage.entity_id</code>.
     */
    public CustomEnvironmentUsageRecord setEntityId(@Nonnull Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.entity_id</code>.
     */
    @Column(name = "entity_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getEntityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>custom_environment_usage.entity_kind</code>.
     */
    public CustomEnvironmentUsageRecord setEntityKind(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.entity_kind</code>.
     */
    @Column(name = "entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    @Override
    public String getEntityKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>custom_environment_usage.created_at</code>.
     */
    public CustomEnvironmentUsageRecord setCreatedAt(@Nullable Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.created_at</code>.
     */
    @Column(name = "created_at", precision = 6)
    @Nullable
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>custom_environment_usage.created_by</code>.
     */
    public CustomEnvironmentUsageRecord setCreatedBy(@Nonnull String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.created_by</code>.
     */
    @Column(name = "created_by", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>custom_environment_usage.provenance</code>.
     */
    public CustomEnvironmentUsageRecord setProvenance(@Nullable String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>custom_environment_usage.provenance</code>.
     */
    @Column(name = "provenance", length = 64)
    @Size(max = 64)
    @Nullable
    @Override
    public String getProvenance() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(ICustomEnvironmentUsage from) {
        setId(from.getId());
        setCustomEnvironmentId(from.getCustomEnvironmentId());
        setEntityId(from.getEntityId());
        setEntityKind(from.getEntityKind());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setProvenance(from.getProvenance());
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomEnvironmentUsageRecord
     */
    public CustomEnvironmentUsageRecord() {
        super(CustomEnvironmentUsage.CUSTOM_ENVIRONMENT_USAGE);
    }

    /**
     * Create a detached, initialised CustomEnvironmentUsageRecord
     */
    @ConstructorProperties({ "id", "customEnvironmentId", "entityId", "entityKind", "createdAt", "createdBy", "provenance" })
    public CustomEnvironmentUsageRecord(@Nullable Long id, @Nonnull Long customEnvironmentId, @Nonnull Long entityId, @Nonnull String entityKind, @Nullable Timestamp createdAt, @Nonnull String createdBy, @Nullable String provenance) {
        super(CustomEnvironmentUsage.CUSTOM_ENVIRONMENT_USAGE);

        setId(id);
        setCustomEnvironmentId(customEnvironmentId);
        setEntityId(entityId);
        setEntityKind(entityKind);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setProvenance(provenance);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomEnvironmentUsageRecord
     */
    public CustomEnvironmentUsageRecord(com.silo.backend.database.tables.pojos.CustomEnvironmentUsage value) {
        super(CustomEnvironmentUsage.CUSTOM_ENVIRONMENT_USAGE);

        if (value != null) {
            setId(value.id());
            setCustomEnvironmentId(value.customEnvironmentId());
            setEntityId(value.entityId());
            setEntityKind(value.entityKind());
            setCreatedAt(value.createdAt());
            setCreatedBy(value.createdBy());
            setProvenance(value.provenance());
            resetChangedOnNotNull();
        }
    }
}
