/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.records;


import com.silo.backend.database.tables.User;
import com.silo.backend.database.tables.interfaces.IUser;

import jakarta.annotation.Nonnull;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user"
)
public class UserRecord extends TableRecordImpl<UserRecord> implements IUser {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user.user_name</code>.
     */
    public UserRecord setUserName(@Nonnull String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.user_name</code>.
     */
    @Column(name = "user_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getUserName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>user.password</code>.
     */
    public UserRecord setPassword(@Nonnull String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.password</code>.
     */
    @Column(name = "password", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getPassword() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IUser from) {
        setUserName(from.getUserName());
        setPassword(from.getPassword());
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    @ConstructorProperties({ "userName", "password" })
    public UserRecord(@Nonnull String userName, @Nonnull String password) {
        super(User.USER);

        setUserName(userName);
        setPassword(password);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(com.silo.backend.database.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setUserName(value.userName());
            setPassword(value.password());
            resetChangedOnNotNull();
        }
    }
}
