/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables;


import com.silo.backend.database.DefaultSchema;
import com.silo.backend.database.tables.records.ApplicationGroupMemberRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * users granted viewer or ownership rights to app groups
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationGroupMember extends TableImpl<ApplicationGroupMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>application_group_member</code>
     */
    public static final ApplicationGroupMember APPLICATION_GROUP_MEMBER = new ApplicationGroupMember();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<ApplicationGroupMemberRecord> getRecordType() {
        return ApplicationGroupMemberRecord.class;
    }

    /**
     * The column <code>application_group_member.group_id</code>. reference to
     * the group this member belongs to
     */
    public final TableField<ApplicationGroupMemberRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT.nullable(false), this, "reference to the group this member belongs to");

    /**
     * The column <code>application_group_member.user_id</code>. reference to
     * the user id of the group member
     */
    public final TableField<ApplicationGroupMemberRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(128).nullable(false), this, "reference to the user id of the group member");

    /**
     * The column <code>application_group_member.role</code>. the role of the
     * user in the group (one of: VIEWER, OWNER)
     */
    public final TableField<ApplicationGroupMemberRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field(DSL.raw("'VIEWER'"), SQLDataType.VARCHAR)), this, "the role of the user in the group (one of: VIEWER, OWNER)");

    private ApplicationGroupMember(Name alias, Table<ApplicationGroupMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ApplicationGroupMember(Name alias, Table<ApplicationGroupMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("users granted viewer or ownership rights to app groups"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>application_group_member</code> table reference
     */
    public ApplicationGroupMember(String alias) {
        this(DSL.name(alias), APPLICATION_GROUP_MEMBER);
    }

    /**
     * Create an aliased <code>application_group_member</code> table reference
     */
    public ApplicationGroupMember(Name alias) {
        this(alias, APPLICATION_GROUP_MEMBER);
    }

    /**
     * Create a <code>application_group_member</code> table reference
     */
    public ApplicationGroupMember() {
        this(DSL.name("application_group_member"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @Nonnull
    public ApplicationGroupMember as(String alias) {
        return new ApplicationGroupMember(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public ApplicationGroupMember as(Name alias) {
        return new ApplicationGroupMember(alias, this);
    }

    @Override
    @Nonnull
    public ApplicationGroupMember as(Table<?> alias) {
        return new ApplicationGroupMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember rename(String name) {
        return new ApplicationGroupMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember rename(Name name) {
        return new ApplicationGroupMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember rename(Table<?> name) {
        return new ApplicationGroupMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember where(Condition condition) {
        return new ApplicationGroupMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationGroupMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationGroupMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationGroupMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationGroupMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationGroupMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
