/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables;


import com.silo.backend.database.DefaultSchema;
import com.silo.backend.database.tables.records.ApplicationComponentRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationComponent extends TableImpl<ApplicationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>application_component</code>
     */
    public static final ApplicationComponent APPLICATION_COMPONENT = new ApplicationComponent();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<ApplicationComponentRecord> getRecordType() {
        return ApplicationComponentRecord.class;
    }

    /**
     * The column <code>application_component.id</code>.
     */
    public final TableField<ApplicationComponentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>application_component.application_id</code>.
     */
    public final TableField<ApplicationComponentRecord, Long> APPLICATION_ID = createField(DSL.name("application_id"), SQLDataType.BIGINT, this, "");

    private ApplicationComponent(Name alias, Table<ApplicationComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ApplicationComponent(Name alias, Table<ApplicationComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>application_component</code> table reference
     */
    public ApplicationComponent(String alias) {
        this(DSL.name(alias), APPLICATION_COMPONENT);
    }

    /**
     * Create an aliased <code>application_component</code> table reference
     */
    public ApplicationComponent(Name alias) {
        this(alias, APPLICATION_COMPONENT);
    }

    /**
     * Create a <code>application_component</code> table reference
     */
    public ApplicationComponent() {
        this(DSL.name("application_component"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @Nonnull
    public ApplicationComponent as(String alias) {
        return new ApplicationComponent(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public ApplicationComponent as(Name alias) {
        return new ApplicationComponent(alias, this);
    }

    @Override
    @Nonnull
    public ApplicationComponent as(Table<?> alias) {
        return new ApplicationComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationComponent rename(String name) {
        return new ApplicationComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationComponent rename(Name name) {
        return new ApplicationComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public ApplicationComponent rename(Table<?> name) {
        return new ApplicationComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent where(Condition condition) {
        return new ApplicationComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public ApplicationComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public ApplicationComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
