/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables;


import com.silo.backend.database.DefaultSchema;
import com.silo.backend.database.tables.records.DatabaseUsageRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DatabaseUsage extends TableImpl<DatabaseUsageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>database_usage</code>
     */
    public static final DatabaseUsage DATABASE_USAGE = new DatabaseUsage();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<DatabaseUsageRecord> getRecordType() {
        return DatabaseUsageRecord.class;
    }

    /**
     * The column <code>database_usage.id</code>.
     */
    public final TableField<DatabaseUsageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>database_usage.database_id</code>.
     */
    public final TableField<DatabaseUsageRecord, Long> DATABASE_ID = createField(DSL.name("database_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>database_usage.entity_kind</code>.
     */
    public final TableField<DatabaseUsageRecord, String> ENTITY_KIND = createField(DSL.name("entity_kind"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>database_usage.entity_id</code>.
     */
    public final TableField<DatabaseUsageRecord, Long> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>database_usage.environment</code>.
     */
    public final TableField<DatabaseUsageRecord, String> ENVIRONMENT = createField(DSL.name("environment"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>database_usage.last_updated_at</code>.
     */
    public final TableField<DatabaseUsageRecord, Timestamp> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.TIMESTAMP(6).nullable(false).defaultValue(DSL.field(DSL.raw("LOCALTIMESTAMP"), SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>database_usage.last_updated_by</code>.
     */
    public final TableField<DatabaseUsageRecord, String> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>database_usage.provenance</code>.
     */
    public final TableField<DatabaseUsageRecord, String> PROVENANCE = createField(DSL.name("provenance"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    private DatabaseUsage(Name alias, Table<DatabaseUsageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DatabaseUsage(Name alias, Table<DatabaseUsageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>database_usage</code> table reference
     */
    public DatabaseUsage(String alias) {
        this(DSL.name(alias), DATABASE_USAGE);
    }

    /**
     * Create an aliased <code>database_usage</code> table reference
     */
    public DatabaseUsage(Name alias) {
        this(alias, DATABASE_USAGE);
    }

    /**
     * Create a <code>database_usage</code> table reference
     */
    public DatabaseUsage() {
        this(DSL.name("database_usage"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @Nonnull
    public Identity<DatabaseUsageRecord, Long> getIdentity() {
        return (Identity<DatabaseUsageRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public DatabaseUsage as(String alias) {
        return new DatabaseUsage(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public DatabaseUsage as(Name alias) {
        return new DatabaseUsage(alias, this);
    }

    @Override
    @Nonnull
    public DatabaseUsage as(Table<?> alias) {
        return new DatabaseUsage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public DatabaseUsage rename(String name) {
        return new DatabaseUsage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public DatabaseUsage rename(Name name) {
        return new DatabaseUsage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public DatabaseUsage rename(Table<?> name) {
        return new DatabaseUsage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage where(Condition condition) {
        return new DatabaseUsage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public DatabaseUsage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public DatabaseUsage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public DatabaseUsage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public DatabaseUsage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public DatabaseUsage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
