-- liquibase formatted sql

-- changeset dobra:1705150791624-1
CREATE TABLE "access_log" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_name" VARCHAR(128) NOT NULL, "state" VARCHAR(255) NOT NULL, "params" VARCHAR(1024), "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "access_log_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "access_log" IS 'logs user page and section views';
COMMENT ON COLUMN "access_log"."user_name" IS 'identifier of the user accessing the page or section';
COMMENT ON COLUMN "access_log"."state" IS 'identifier of the page  plus optionally a section identifier (format: state|section)';
COMMENT ON COLUMN "access_log"."params" IS 'additional params provided to page/section';

-- changeset dobra:1705150791624-2
CREATE TABLE "application" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "description" VARCHAR(4000), "asset_code" VARCHAR(255), "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "organisational_unit_id" BIGINT NOT NULL, "kind" VARCHAR(128) DEFAULT 'IN_HOUSE' NOT NULL, "lifecycle_phase" VARCHAR(128) DEFAULT 'PRODUCTION' NOT NULL, "parent_asset_code" VARCHAR(255), "overall_rating" CHAR(1) DEFAULT 'Z' NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, "business_criticality" VARCHAR(128) DEFAULT 'UNKNOWN' NOT NULL, "is_removed" BOOLEAN DEFAULT FALSE NOT NULL, "entity_lifecycle_status" VARCHAR(64) DEFAULT 'ACTIVE' NOT NULL, "planned_retirement_date" TIMESTAMP WITHOUT TIME ZONE, "actual_retirement_date" TIMESTAMP WITHOUT TIME ZONE, "commission_date" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "application_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "application" IS 'represents an application (with an entity_kind of ''APPLICATION'')';
COMMENT ON COLUMN "application"."name" IS 'name of this application (aliases can be added in the entity_alias table)';
COMMENT ON COLUMN "application"."description" IS 'longer description to provide more information about this application.  Markdown is supported';
COMMENT ON COLUMN "application"."asset_code" IS 'external identifier representing this application';
COMMENT ON COLUMN "application"."organisational_unit_id" IS 'reference to the owning org unit';
COMMENT ON COLUMN "application"."kind" IS 'broad category of this application (e.g. IN_HOUSE, EXTERNALLY_HOSTED, THIRD_PARTY, EUC, etc)';
COMMENT ON COLUMN "application"."lifecycle_phase" IS 'the current application lifecycle state of this application (one of: CONCEPTUAL, DEVELOPMENT, PRODUCTION, RETIRED)';
COMMENT ON COLUMN "application"."parent_asset_code" IS 'asset code of any parent application';
COMMENT ON COLUMN "application"."overall_rating" IS 'investment rating scheme (one of: R, A, G, Z / which equates to Disinvest, Maintain, Invest, Unknown)';
COMMENT ON COLUMN "application"."provenance" IS 'origination of this application record.  Will be ''waltz'' if entered via the UI';
COMMENT ON COLUMN "application"."business_criticality" IS 'business criticality of this application (one of: LOW, MEDIUM, HIGH, VERY_HIGH, NONE, UNKNOWN)';
COMMENT ON COLUMN "application"."is_removed" IS 'should this record logically be treated as if it has been physically deleted';
COMMENT ON COLUMN "application"."entity_lifecycle_status" IS 'the lifecycle state of this entity record, slightly different from is_removed as does not imply the record is ''gone''  (one of: ACTIVE, PENDING, REMOVED)';
COMMENT ON COLUMN "application"."planned_retirement_date" IS 'date when this application is (or was) planning to retire';
COMMENT ON COLUMN "application"."actual_retirement_date" IS 'date when this application actually retired from production, null if not planned';
COMMENT ON COLUMN "application"."commission_date" IS 'when was this application commissioned, null if unknown';

-- changeset dobra:1705150791624-3
CREATE TABLE "organisational_unit" ("id" BIGINT NOT NULL, "name" VARCHAR(255), "description" VARCHAR(4000), "parent_id" BIGINT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "external_id" VARCHAR(200), "created_by" VARCHAR(255) DEFAULT 'waltz' NOT NULL, "updated_by" VARCHAR(255) DEFAULT 'waltz' NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, CONSTRAINT "organisational_unit_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-4
CREATE TABLE "server_information" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "hostname" VARCHAR(255) NOT NULL, "operating_system" VARCHAR(128) DEFAULT 'UNKNOWN' NOT NULL, "location" VARCHAR(128) NOT NULL, "operating_system_version" VARCHAR(128) NOT NULL, "country" VARCHAR(128) NOT NULL, "is_virtual" BOOLEAN, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, "os_end_of_life_date" date, "hw_end_of_life_date" date, "lifecycle_status" VARCHAR(64) DEFAULT 'UNKNOWN' NOT NULL, "external_id" VARCHAR(200), CONSTRAINT "server_information_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-5
CREATE TABLE "application_group" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "kind" VARCHAR(64) DEFAULT 'PUBLIC' NOT NULL, "description" TEXT, "external_id" VARCHAR(200), "is_removed" BOOLEAN DEFAULT FALSE NOT NULL, "is_favourite_group" BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT "application_group_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "application_group" IS 'represents an ad-hoc collection of applications';
COMMENT ON COLUMN "application_group"."name" IS 'display name for the group';
COMMENT ON COLUMN "application_group"."kind" IS 'the type of group (one of: PUBLIC, PRIVATE).  Note, private groups can still be seen, they are merely unlisted in the UI';
COMMENT ON COLUMN "application_group"."description" IS 'longer description of the group, supports markdown';
COMMENT ON COLUMN "application_group"."external_id" IS 'external identifier, typically used when creating/syncing groups via external jobs';
COMMENT ON COLUMN "application_group"."is_removed" IS 'flag indicating if the group has been deleted';
COMMENT ON COLUMN "application_group"."is_favourite_group" IS 'a favourite group is assigned to each user to allow them to quickly bookmark apps and populate the change calendar on the homepage';

-- changeset dobra:1705150791624-6
CREATE TABLE "application_group_member" ("group_id" BIGINT NOT NULL, "user_id" VARCHAR(128) NOT NULL, "role" VARCHAR(64) DEFAULT 'VIEWER' NOT NULL, CONSTRAINT "application_group_member_pkey" PRIMARY KEY ("group_id", "user_id"));
COMMENT ON TABLE "application_group_member" IS 'users granted viewer or ownership rights to app groups';
COMMENT ON COLUMN "application_group_member"."group_id" IS 'reference to the group this member belongs to';
COMMENT ON COLUMN "application_group_member"."user_id" IS 'reference to the user id of the group member';
COMMENT ON COLUMN "application_group_member"."role" IS 'the role of the user in the group (one of: VIEWER, OWNER)';

-- changeset dobra:1705150791624-7
CREATE TABLE "settings" ("name" VARCHAR(128) NOT NULL, "value" VARCHAR(4000), "restricted" BOOLEAN DEFAULT FALSE NOT NULL, "description" VARCHAR(4000), CONSTRAINT "settings_pkey" PRIMARY KEY ("name"));
COMMENT ON TABLE "settings" IS 'contains configuration data which controls the operation of Waltz.';
COMMENT ON COLUMN "settings"."name" IS 'the key name of the setting, often uses dotted notation.  Strongly recommended to put client specific settings under their own namespace (i.e. mycorp.somesetting)';
COMMENT ON COLUMN "settings"."value" IS 'the value of the setting, if the setting is a boolean it should be entered as lowercase';
COMMENT ON COLUMN "settings"."restricted" IS 'restricted settings are internal to Waltz and not available via API/external calls';
COMMENT ON COLUMN "settings"."description" IS 'optional comment to describe this setting';

-- changeset dobra:1705150791624-8
CREATE TABLE "actor" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "description" VARCHAR(4000) NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_by" VARCHAR(255) NOT NULL, "is_external" BOOLEAN DEFAULT FALSE NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, "external_id" VARCHAR(200), CONSTRAINT "actor_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "actor" IS 'represents a non application entity, typically used in flows.  Examples include exchanges, departments, counterpart organisations';
COMMENT ON COLUMN "actor"."name" IS 'short name identifying the actor (i.e. Bank of England)';
COMMENT ON COLUMN "actor"."description" IS 'longer textual description of the actor';
COMMENT ON COLUMN "actor"."is_external" IS 'flag to indicate whether this is an internal actor (e.g. Chief Risk Officer) or external actor (e.g. Bank of England)';
COMMENT ON COLUMN "actor"."provenance" IS 'where did this actor record originate, will be ''waltz'' if provided via the UI';
COMMENT ON COLUMN "actor"."external_id" IS 'identifier this actor is known by externally.  Should not change, unlike the name which may change.';

-- changeset dobra:1705150791624-9
CREATE TABLE "person" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "employee_id" VARCHAR(128), "display_name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, "user_principal_name" VARCHAR(255), "department_name" VARCHAR(255), "kind" VARCHAR(255) NOT NULL, "manager_employee_id" VARCHAR(128), "title" VARCHAR(255), "office_phone" VARCHAR(128), "mobile_phone" VARCHAR(128), "organisational_unit_id" BIGINT, "is_removed" BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT "person_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-10
CREATE TABLE "server_usage" ("server_id" BIGINT NOT NULL, "entity_kind" VARCHAR(64) NOT NULL, "entity_id" BIGINT NOT NULL, "environment" VARCHAR(64) DEFAULT 'UNKNOWN' NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" VARCHAR(255) NOT NULL, "provenance" VARCHAR(64) NOT NULL, "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "server_usage_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-11
CREATE TABLE "thumbnail" ("parent_entity_kind" VARCHAR(64) NOT NULL, "parent_entity_id" BIGINT NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" VARCHAR(255) NOT NULL, "mime_type" VARCHAR(255) NOT NULL, "blob" BYTEA NOT NULL, "external_id" VARCHAR(200), "provenance" VARCHAR(64) NOT NULL);

-- changeset dobra:1705150791624-12
CREATE TABLE "relationship_kind" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "description" VARCHAR(4000), "kind_a" VARCHAR(128) NOT NULL, "kind_b" VARCHAR(128) NOT NULL, "category_a" BIGINT, "category_b" BIGINT, "is_readonly" BOOLEAN DEFAULT FALSE NOT NULL, "code" VARCHAR(128) NOT NULL, "position" INTEGER DEFAULT 0 NOT NULL, "reverse_name" VARCHAR(255) NOT NULL, CONSTRAINT "relationship_kind_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "relationship_kind" IS 'Describes types of relationships between entities';
COMMENT ON COLUMN "relationship_kind"."category_a" IS 'Placeholder: if kind_a is a MEASURABLE then this may (optionally) be used to restrict it based on category';
COMMENT ON COLUMN "relationship_kind"."category_b" IS 'Placeholder: if kind_b is a MEASURABLE then this may (optionally) be used to restrict it based on category';

-- changeset dobra:1705150791624-13
CREATE TABLE "application_group_entry" ("group_id" BIGINT NOT NULL, "application_id" BIGINT NOT NULL, "is_readonly" BOOLEAN DEFAULT FALSE NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT "application_group_entry_pkey" PRIMARY KEY ("group_id", "application_id"));
COMMENT ON TABLE "application_group_entry" IS 'a reference to a specific application in a group';
COMMENT ON COLUMN "application_group_entry"."group_id" IS 'reference to the group this entry belongs to';
COMMENT ON COLUMN "application_group_entry"."application_id" IS 'reference to the application this entry refers to';
COMMENT ON COLUMN "application_group_entry"."is_readonly" IS 'flag to indicate that the value is readonly.  Typically set if group entries are added by external jobs';
COMMENT ON COLUMN "application_group_entry"."provenance" IS 'indicates where this record originated. Will be ''waltz'' if created via the UI';
COMMENT ON COLUMN "application_group_entry"."created_at" IS 'the date this entry was created, sometimes used to ''age'' entries out the group, i.e. in exception lists';

-- changeset dobra:1705150791624-14
CREATE TABLE "application_group_ou_entry" ("group_id" BIGINT NOT NULL, "org_unit_id" BIGINT NOT NULL, "is_readonly" BOOLEAN DEFAULT FALSE NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT "app_group_ou_entry_pkey" PRIMARY KEY ("group_id", "org_unit_id"));
COMMENT ON TABLE "application_group_ou_entry" IS 'app groups can include reference to org units. Apps associated to the org unit are included in the group at runtime';
COMMENT ON COLUMN "application_group_ou_entry"."group_id" IS 'reference to the group this entry belongs to';
COMMENT ON COLUMN "application_group_ou_entry"."org_unit_id" IS 'reference to the org unit this entry belongs to';
COMMENT ON COLUMN "application_group_ou_entry"."is_readonly" IS 'flag to indicate that the value is readonly.  Typically set if group entries are added by external jobs';
COMMENT ON COLUMN "application_group_ou_entry"."provenance" IS 'indicates where this record originated. Will be ''waltz'' if created via the UI';
COMMENT ON COLUMN "application_group_ou_entry"."created_at" IS 'the date this entry was created';

-- changeset dobra:1705150791624-15
CREATE TABLE "complexity_kind" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "description" VARCHAR(4000), "external_id" VARCHAR(200), "is_default" BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT "complexity_kind_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "complexity_kind" IS 'complexity can be used to give a decimal score for an entity in waltz against a complexity kind (e.g. Flow Complexity). The complexity kind describes the type of complexity being evaluated.';
COMMENT ON COLUMN "complexity_kind"."id" IS 'unique identifier for this complexity kind record within waltz';
COMMENT ON COLUMN "complexity_kind"."name" IS 'the name of this complexity kind';
COMMENT ON COLUMN "complexity_kind"."description" IS 'longer description to provide more information about this complexity kind';
COMMENT ON COLUMN "complexity_kind"."external_id" IS 'external identifier for this complexity kind';
COMMENT ON COLUMN "complexity_kind"."is_default" IS 'indicates the complexity kind to be shown on the entity overview by default';

-- changeset dobra:1705150791624-16
CREATE TABLE "complexity" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "complexity_kind_id" BIGINT NOT NULL, "entity_id" BIGINT NOT NULL, "entity_kind" VARCHAR(64) NOT NULL, "score" numeric(10, 3) NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" VARCHAR(255) NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, CONSTRAINT "complexity_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "complexity" IS 'a score of a given complexity kind for an entity in waltz';
COMMENT ON COLUMN "complexity"."id" IS 'unique identifier for this complexity record within waltz';
COMMENT ON COLUMN "complexity"."complexity_kind_id" IS 'the reference to the complexity kind that describes this score';
COMMENT ON COLUMN "complexity"."entity_id" IS 'the identifier for the entity this score belongs to';
COMMENT ON COLUMN "complexity"."entity_kind" IS 'the kind of the entity this score belongs to';
COMMENT ON COLUMN "complexity"."score" IS 'the value of the complexity, the value should fall between 0 and 1 indicating proximity to a baseline (up to 3 decimal places)';
COMMENT ON COLUMN "complexity"."updated_at" IS 'the datetime this complexity record was last updated';
COMMENT ON COLUMN "complexity"."updated_by" IS 'the last user to update this complexity record';
COMMENT ON COLUMN "complexity"."provenance" IS 'origination of this change unit record';

-- changeset dobra:1705150791624-17
CREATE TABLE "database_usage" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "database_id" BIGINT NOT NULL, "entity_kind" VARCHAR(64) NOT NULL, "entity_id" BIGINT NOT NULL, "environment" VARCHAR(64) NOT NULL, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" VARCHAR(255) NOT NULL, "provenance" VARCHAR(64) NOT NULL, CONSTRAINT "database_usage_id_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-18
CREATE TABLE "database_information" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "database_name" VARCHAR(255) DEFAULT 'waltz' NOT NULL, "instance_name" VARCHAR(255) DEFAULT 'waltz' NOT NULL, "dbms_vendor" VARCHAR(255) NOT NULL, "dbms_name" VARCHAR(255) NOT NULL, "dbms_version" VARCHAR(128) NOT NULL, "external_id" VARCHAR(200) DEFAULT 'waltz', "end_of_life_date" date, "lifecycle_status" VARCHAR(64), "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, CONSTRAINT "database_information_2_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-19
CREATE TABLE "custom_environment" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "owning_entity_id" BIGINT NOT NULL, "owning_entity_kind" VARCHAR(64) NOT NULL, "name" VARCHAR(255) NOT NULL, "description" VARCHAR(4000), "external_id" VARCHAR(200) NOT NULL, "group_name" VARCHAR(255) DEFAULT 'Default' NOT NULL, CONSTRAINT "custom_environment_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-20
CREATE TABLE "custom_environment_usage" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "custom_environment_id" BIGINT NOT NULL, "entity_id" BIGINT NOT NULL, "entity_kind" VARCHAR(64) NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" VARCHAR(255) NOT NULL, "provenance" VARCHAR(64) DEFAULT 'waltz' NOT NULL, CONSTRAINT "custom_env_usage_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-21
CREATE INDEX "idx_asset_code" ON "application"("asset_code");

-- changeset dobra:1705150791624-22
CREATE INDEX "idx_organisational_unit_id" ON "application"("organisational_unit_id");

-- changeset dobra:1705150791624-23
CREATE INDEX "idx_els_application" ON "application"("entity_lifecycle_status");

-- changeset dobra:1705150791624-24
CREATE UNIQUE INDEX "idx_si_hostname" ON "server_information"("hostname");

-- changeset dobra:1705150791624-25
CREATE UNIQUE INDEX "idx_si_external_id" ON "server_information"("external_id");

-- changeset dobra:1705150791624-26
CREATE TABLE "role" ("key" VARCHAR(255) NOT NULL, "is_custom" BOOLEAN DEFAULT TRUE NOT NULL, "name" VARCHAR(255) NOT NULL, "description" VARCHAR(4000) NOT NULL, "user_selectable" BOOLEAN DEFAULT TRUE NOT NULL, CONSTRAINT "role_pkey" PRIMARY KEY ("key"));

-- changeset dobra:1705150791624-27
ALTER TABLE "actor" ADD CONSTRAINT "involvement_kind_name_key" UNIQUE ("name");

-- changeset dobra:1705150791624-28
ALTER TABLE "actor" ADD CONSTRAINT "unique_actor_ext_id" UNIQUE ("external_id");

-- changeset dobra:1705150791624-29
CREATE INDEX "idx_person_email" ON "person"("email");

-- changeset dobra:1705150791624-30
ALTER TABLE "person" ADD CONSTRAINT "unique_employee_id" UNIQUE ("employee_id");

-- changeset dobra:1705150791624-31
ALTER TABLE "person" ADD CONSTRAINT "unq_person_organisational_unit_id" UNIQUE ("organisational_unit_id");

-- changeset dobra:1705150791624-32
CREATE UNIQUE INDEX "idx_su_s_id_id_kind_env" ON "server_usage"("server_id", "entity_id", "entity_kind", "environment");

-- changeset dobra:1705150791624-33
ALTER TABLE "server_usage" ADD CONSTRAINT "unq_server_usage_environment" UNIQUE ("environment");

-- changeset dobra:1705150791624-34
ALTER TABLE "relationship_kind" ADD CONSTRAINT "unique_rel_kind" UNIQUE ("kind_a", "kind_b", "code");

-- changeset dobra:1705150791624-35
ALTER TABLE "database_usage" ADD CONSTRAINT "unq_database_usage_environment" UNIQUE ("environment");

-- changeset dobra:1705150791624-36
CREATE UNIQUE INDEX "idx_owning_entity_name" ON "custom_environment"("name", "owning_entity_kind", "owning_entity_id");

-- changeset dobra:1705150791624-37
CREATE UNIQUE INDEX "idx_env_id_entity" ON "custom_environment_usage"("custom_environment_id", "entity_kind", "entity_id");

-- changeset dobra:1705150791624-38
CREATE TABLE "application_component" ("id" BIGINT NOT NULL, "application_id" BIGINT, CONSTRAINT "pk_application_component" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-39
CREATE TABLE "application_relationship" ("id" BIGINT NOT NULL, "relation_kind" BIGINT, CONSTRAINT "pk_application_relationship" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-40
CREATE TABLE "user" ("user_name" VARCHAR(128) NOT NULL, "password" VARCHAR(255) NOT NULL, CONSTRAINT "user_pkey" PRIMARY KEY ("user_name"));

-- changeset dobra:1705150791624-41
CREATE TABLE "user_agent_info" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_name" VARCHAR(128) NOT NULL, "user_agent" VARCHAR(500) NOT NULL, "resolution" VARCHAR(128) NOT NULL, "operating_system" VARCHAR(128) NOT NULL, "ip_address" VARCHAR(128) NOT NULL, "login_timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT "user_agent_info_pkey" PRIMARY KEY ("id"));

-- changeset dobra:1705150791624-42
CREATE TABLE "user_preference" ("key" VARCHAR(120) NOT NULL, "value" VARCHAR(2048) NOT NULL, "user_name" VARCHAR(128) NOT NULL);

-- changeset dobra:1705150791624-43
CREATE TABLE "user_role" ("user_name" VARCHAR(255) NOT NULL, "role" VARCHAR(255) NOT NULL, CONSTRAINT "user_role_pkey" PRIMARY KEY ("user_name", "role"));

-- changeset dobra:1705150791624-44
ALTER TABLE "thumbnail" ADD CONSTRAINT "thumbnail_pkey" PRIMARY KEY ("parent_entity_id", "parent_entity_kind");

-- changeset dobra:1705150791624-45
ALTER TABLE "user_preference" ADD CONSTRAINT "user_preference_pkey" PRIMARY KEY ("user_name", "key");

-- changeset dobra:1705150791624-46
ALTER TABLE "application_group_ou_entry" ADD CONSTRAINT "app_grp_ou_entry_grp_id_fkey" FOREIGN KEY ("group_id") REFERENCES "application_group" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-47
ALTER TABLE "application_group_entry" ADD CONSTRAINT "application_group_entry_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "application_group" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-48
ALTER TABLE "application_group_member" ADD CONSTRAINT "application_group_member_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "application_group" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-49
ALTER TABLE "complexity" ADD CONSTRAINT "complexity_to_complexity_kind_id_fk" FOREIGN KEY ("complexity_kind_id") REFERENCES "complexity_kind" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-50
ALTER TABLE "custom_environment_usage" ADD CONSTRAINT "custom_env_usage_to_custom_env_fk" FOREIGN KEY ("custom_environment_id") REFERENCES "custom_environment" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-51
ALTER TABLE "database_usage" ADD CONSTRAINT "database_usage_database_id_fk" FOREIGN KEY ("database_id") REFERENCES "database_information" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-52
ALTER TABLE "access_log" ADD CONSTRAINT "fk_access_log_user" FOREIGN KEY ("user_name") REFERENCES "user" ("user_name") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-53
ALTER TABLE "application_component" ADD CONSTRAINT "fk_application_component_application" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-54
ALTER TABLE "application_group_entry" ADD CONSTRAINT "fk_application_group_entry_application" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-55
ALTER TABLE "application_group_ou_entry" ADD CONSTRAINT "fk_application_group_ou_entry_organisational_unit" FOREIGN KEY ("org_unit_id") REFERENCES "organisational_unit" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-56
ALTER TABLE "organisational_unit" ADD CONSTRAINT "fk_organisational_unit_person" FOREIGN KEY ("id") REFERENCES "person" ("organisational_unit_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-57
ALTER TABLE "user_agent_info" ADD CONSTRAINT "fk_user_agent_info_user" FOREIGN KEY ("user_name") REFERENCES "user" ("user_name") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-58
ALTER TABLE "user_preference" ADD CONSTRAINT "fk_user_preference_user" FOREIGN KEY ("user_name") REFERENCES "user" ("user_name") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset dobra:1705150791624-59
ALTER TABLE "server_usage" ADD CONSTRAINT "server_usage_server_id_fk" FOREIGN KEY ("server_id") REFERENCES "server_information" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-60
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_role_key_fk" FOREIGN KEY ("role") REFERENCES "role" ("key") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset dobra:1705150791624-61
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_user_name_fkey" FOREIGN KEY ("user_name") REFERENCES "user" ("user_name") ON UPDATE NO ACTION ON DELETE CASCADE;

