/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.pojos;


import com.silo.backend.database.tables.interfaces.IApplicationGroup;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;


/**
 * represents an ad-hoc collection of applications
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "application_group"
)
public record ApplicationGroup(
    @Nullable Long id,
    @Nonnull String name,
    @Nullable String kind,
    @Nullable String description,
    @Nullable String externalId,
    @Nullable Boolean isRemoved,
    @Nullable Boolean isFavouriteGroup
) implements IApplicationGroup {

    private static final long serialVersionUID = 1L;


    /**
     * Getter for <code>application_group.id</code>.
     */
    @Column(name = "id")
    @Nullable
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>application_group.name</code>. display name for the
     * group
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>application_group.kind</code>. the type of group (one
     * of: PUBLIC, PRIVATE).  Note, private groups can still be seen, they are
     * merely unlisted in the UI
     */
    @Column(name = "kind", length = 64)
    @Size(max = 64)
    @Nullable
    @Override
    public String getKind() {
        return this.kind;
    }

    /**
     * Getter for <code>application_group.description</code>. longer description
     * of the group, supports markdown
     */
    @Column(name = "description", length = 1000000000)
    @Size(max = 1000000000)
    @Nullable
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>application_group.external_id</code>. external
     * identifier, typically used when creating/syncing groups via external jobs
     */
    @Column(name = "external_id", length = 200)
    @Size(max = 200)
    @Nullable
    @Override
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Getter for <code>application_group.is_removed</code>. flag indicating if
     * the group has been deleted
     */
    @Column(name = "is_removed")
    @Nullable
    @Override
    public Boolean getIsRemoved() {
        return this.isRemoved;
    }

    /**
     * Getter for <code>application_group.is_favourite_group</code>. a favourite
     * group is assigned to each user to allow them to quickly bookmark apps and
     * populate the change calendar on the homepage
     */
    @Column(name = "is_favourite_group")
    @Nullable
    @Override
    public Boolean getIsFavouriteGroup() {
        return this.isFavouriteGroup;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ApplicationGroup other = (ApplicationGroup) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.kind == null) {
            if (other.kind != null)
                return false;
        }
        else if (!this.kind.equals(other.kind))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.isRemoved == null) {
            if (other.isRemoved != null)
                return false;
        }
        else if (!this.isRemoved.equals(other.isRemoved))
            return false;
        if (this.isFavouriteGroup == null) {
            if (other.isFavouriteGroup != null)
                return false;
        }
        else if (!this.isFavouriteGroup.equals(other.isFavouriteGroup))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.kind == null) ? 0 : this.kind.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.isRemoved == null) ? 0 : this.isRemoved.hashCode());
        result = prime * result + ((this.isFavouriteGroup == null) ? 0 : this.isFavouriteGroup.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(kind);
        sb.append(", ").append(description);
        sb.append(", ").append(externalId);
        sb.append(", ").append(isRemoved);
        sb.append(", ").append(isFavouriteGroup);

        sb.append(")");
        return sb.toString();
    }
}
