/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.pojos;


import com.silo.backend.database.tables.interfaces.IApplicationGroupMember;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;


/**
 * users granted viewer or ownership rights to app groups
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "application_group_member"
)
public record ApplicationGroupMember(
    @Nonnull Long groupId,
    @Nonnull String userId,
    @Nullable String role
) implements IApplicationGroupMember {

    private static final long serialVersionUID = 1L;


    /**
     * Getter for <code>application_group_member.group_id</code>. reference to
     * the group this member belongs to
     */
    @Column(name = "group_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Getter for <code>application_group_member.user_id</code>. reference to
     * the user id of the group member
     */
    @Column(name = "user_id", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    @Override
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>application_group_member.role</code>. the role of the
     * user in the group (one of: VIEWER, OWNER)
     */
    @Column(name = "role", length = 64)
    @Size(max = 64)
    @Nullable
    @Override
    public String getRole() {
        return this.role;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ApplicationGroupMember other = (ApplicationGroupMember) obj;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationGroupMember (");

        sb.append(groupId);
        sb.append(", ").append(userId);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
