/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.pojos;


import com.silo.backend.database.tables.interfaces.IComplexity;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * a score of a given complexity kind for an entity in waltz
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "complexity"
)
public record Complexity(
    @Nullable Long id,
    @Nonnull Long complexityKindId,
    @Nonnull Long entityId,
    @Nonnull String entityKind,
    @Nonnull BigDecimal score,
    @Nullable Timestamp lastUpdatedAt,
    @Nonnull String lastUpdatedBy,
    @Nullable String provenance
) implements IComplexity {

    private static final long serialVersionUID = 1L;


    /**
     * Getter for <code>complexity.id</code>. unique identifier for this
     * complexity record within waltz
     */
    @Column(name = "id")
    @Nullable
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>complexity.complexity_kind_id</code>. the reference to
     * the complexity kind that describes this score
     */
    @Column(name = "complexity_kind_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getComplexityKindId() {
        return this.complexityKindId;
    }

    /**
     * Getter for <code>complexity.entity_id</code>. the identifier for the
     * entity this score belongs to
     */
    @Column(name = "entity_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getEntityId() {
        return this.entityId;
    }

    /**
     * Getter for <code>complexity.entity_kind</code>. the kind of the entity
     * this score belongs to
     */
    @Column(name = "entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    @Override
    public String getEntityKind() {
        return this.entityKind;
    }

    /**
     * Getter for <code>complexity.score</code>. the value of the complexity,
     * the value should fall between 0 and 1 indicating proximity to a baseline
     * (up to 3 decimal places)
     */
    @Column(name = "score", nullable = false, precision = 10, scale = 3)
    @NotNull
    @Nonnull
    @Override
    public BigDecimal getScore() {
        return this.score;
    }

    /**
     * Getter for <code>complexity.last_updated_at</code>. the datetime this
     * complexity record was last updated
     */
    @Column(name = "last_updated_at", precision = 6)
    @Nullable
    @Override
    public Timestamp getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    /**
     * Getter for <code>complexity.last_updated_by</code>. the last user to
     * update this complexity record
     */
    @Column(name = "last_updated_by", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    /**
     * Getter for <code>complexity.provenance</code>. origination of this change
     * unit record
     */
    @Column(name = "provenance", length = 64)
    @Size(max = 64)
    @Nullable
    @Override
    public String getProvenance() {
        return this.provenance;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Complexity other = (Complexity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.complexityKindId == null) {
            if (other.complexityKindId != null)
                return false;
        }
        else if (!this.complexityKindId.equals(other.complexityKindId))
            return false;
        if (this.entityId == null) {
            if (other.entityId != null)
                return false;
        }
        else if (!this.entityId.equals(other.entityId))
            return false;
        if (this.entityKind == null) {
            if (other.entityKind != null)
                return false;
        }
        else if (!this.entityKind.equals(other.entityKind))
            return false;
        if (this.score == null) {
            if (other.score != null)
                return false;
        }
        else if (!this.score.equals(other.score))
            return false;
        if (this.lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!this.lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        if (this.lastUpdatedBy == null) {
            if (other.lastUpdatedBy != null)
                return false;
        }
        else if (!this.lastUpdatedBy.equals(other.lastUpdatedBy))
            return false;
        if (this.provenance == null) {
            if (other.provenance != null)
                return false;
        }
        else if (!this.provenance.equals(other.provenance))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.complexityKindId == null) ? 0 : this.complexityKindId.hashCode());
        result = prime * result + ((this.entityId == null) ? 0 : this.entityId.hashCode());
        result = prime * result + ((this.entityKind == null) ? 0 : this.entityKind.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        result = prime * result + ((this.lastUpdatedBy == null) ? 0 : this.lastUpdatedBy.hashCode());
        result = prime * result + ((this.provenance == null) ? 0 : this.provenance.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Complexity (");

        sb.append(id);
        sb.append(", ").append(complexityKindId);
        sb.append(", ").append(entityId);
        sb.append(", ").append(entityKind);
        sb.append(", ").append(score);
        sb.append(", ").append(lastUpdatedAt);
        sb.append(", ").append(lastUpdatedBy);
        sb.append(", ").append(provenance);

        sb.append(")");
        return sb.toString();
    }
}
