/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.pojos;


import com.silo.backend.database.tables.interfaces.IKeyInvolvementKind;

import jakarta.annotation.Nonnull;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;


/**
 * Key Involvement Kind For Entity Kind
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "key_involvement_kind"
)
public record KeyInvolvementKind(
    @Nonnull Long involvementKindId,
    @Nonnull String entityKind
) implements IKeyInvolvementKind {

    private static final long serialVersionUID = 1L;


    /**
     * Getter for <code>key_involvement_kind.involvement_kind_id</code>.
     */
    @Column(name = "involvement_kind_id", nullable = false)
    @NotNull
    @Nonnull
    @Override
    public Long getInvolvementKindId() {
        return this.involvementKindId;
    }

    /**
     * Getter for <code>key_involvement_kind.entity_kind</code>.
     */
    @Column(name = "entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    @Override
    public String getEntityKind() {
        return this.entityKind;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final KeyInvolvementKind other = (KeyInvolvementKind) obj;
        if (this.involvementKindId == null) {
            if (other.involvementKindId != null)
                return false;
        }
        else if (!this.involvementKindId.equals(other.involvementKindId))
            return false;
        if (this.entityKind == null) {
            if (other.entityKind != null)
                return false;
        }
        else if (!this.entityKind.equals(other.entityKind))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.involvementKindId == null) ? 0 : this.involvementKindId.hashCode());
        result = prime * result + ((this.entityKind == null) ? 0 : this.entityKind.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KeyInvolvementKind (");

        sb.append(involvementKindId);
        sb.append(", ").append(entityKind);

        sb.append(")");
        return sb.toString();
    }
}
