/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.pojos;


import com.silo.backend.database.tables.interfaces.IPermissionGroup;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;


/**
 * group describing the permissions different involvement kinds have against
 * waltz entities
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "permission_group"
)
public record PermissionGroup(
    @Nullable Long id,
    @Nonnull String name,
    @Nonnull String externalId,
    @Nullable String description,
    @Nonnull String provenance,
    @Nullable Boolean isDefault
) implements IPermissionGroup {

    private static final long serialVersionUID = 1L;


    /**
     * Getter for <code>permission_group.id</code>. unique identifier for this
     * cost record within waltz
     */
    @Column(name = "id")
    @Nullable
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>permission_group.name</code>. name of the permission
     * group
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>permission_group.external_id</code>. external identifier
     * for this permission group
     */
    @Column(name = "external_id", nullable = false, length = 200)
    @NotNull
    @Size(max = 200)
    @Nonnull
    @Override
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Getter for <code>permission_group.description</code>. longer description
     * to provide more information about this permission group
     */
    @Column(name = "description", length = 4000)
    @Size(max = 4000)
    @Nullable
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>permission_group.provenance</code>. origination of this
     * permission group
     */
    @Column(name = "provenance", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    @Override
    public String getProvenance() {
        return this.provenance;
    }

    /**
     * Getter for <code>permission_group.is_default</code>. flag to identify the
     * default permission group
     */
    @Column(name = "is_default")
    @Nullable
    @Override
    public Boolean getIsDefault() {
        return this.isDefault;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PermissionGroup other = (PermissionGroup) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.provenance == null) {
            if (other.provenance != null)
                return false;
        }
        else if (!this.provenance.equals(other.provenance))
            return false;
        if (this.isDefault == null) {
            if (other.isDefault != null)
                return false;
        }
        else if (!this.isDefault.equals(other.isDefault))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.provenance == null) ? 0 : this.provenance.hashCode());
        result = prime * result + ((this.isDefault == null) ? 0 : this.isDefault.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissionGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(externalId);
        sb.append(", ").append(description);
        sb.append(", ").append(provenance);
        sb.append(", ").append(isDefault);

        sb.append(")");
        return sb.toString();
    }
}
