/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * app groups can include reference to org units. Apps associated to the org
 * unit are included in the group at runtime
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "application_group_ou_entry"
)
public interface IApplicationGroupOuEntry extends Serializable {

    /**
     * Getter for <code>application_group_ou_entry.group_id</code>. reference to
     * the group this entry belongs to
     */
    @Column(name = "group_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getGroupId();

    /**
     * Getter for <code>application_group_ou_entry.org_unit_id</code>. reference
     * to the org unit this entry belongs to
     */
    @Column(name = "org_unit_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getOrgUnitId();

    /**
     * Getter for <code>application_group_ou_entry.is_readonly</code>. flag to
     * indicate that the value is readonly.  Typically set if group entries are
     * added by external jobs
     */
    @Column(name = "is_readonly")
    @Nullable
    public Boolean getIsReadonly();

    /**
     * Getter for <code>application_group_ou_entry.provenance</code>. indicates
     * where this record originated. Will be 'waltz' if created via the UI
     */
    @Column(name = "provenance", length = 64)
    @Size(max = 64)
    @Nullable
    public String getProvenance();

    /**
     * Getter for <code>application_group_ou_entry.created_at</code>. the date
     * this entry was created
     */
    @Column(name = "created_at", precision = 6)
    @Nullable
    public Timestamp getCreatedAt();
}
