/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "application_relationship"
)
public interface IApplicationRelationship extends Serializable {

    /**
     * Getter for <code>application_relationship.id</code>.
     */
    @Column(name = "id", nullable = false)
    @NotNull
    @Nonnull
    public Long getId();

    /**
     * Getter for <code>application_relationship.relation_kind</code>.
     */
    @Column(name = "relation_kind")
    @Nullable
    public Long getRelationKind();
}
