/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "database_usage"
)
public interface IDatabaseUsage extends Serializable {

    /**
     * Getter for <code>database_usage.id</code>.
     */
    @Column(name = "id")
    @Nullable
    public Long getId();

    /**
     * Getter for <code>database_usage.database_id</code>.
     */
    @Column(name = "database_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getDatabaseId();

    /**
     * Getter for <code>database_usage.entity_kind</code>.
     */
    @Column(name = "entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getEntityKind();

    /**
     * Getter for <code>database_usage.entity_id</code>.
     */
    @Column(name = "entity_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getEntityId();

    /**
     * Getter for <code>database_usage.environment</code>.
     */
    @Column(name = "environment", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getEnvironment();

    /**
     * Getter for <code>database_usage.last_updated_at</code>.
     */
    @Column(name = "last_updated_at", precision = 6)
    @Nullable
    public Timestamp getLastUpdatedAt();

    /**
     * Getter for <code>database_usage.last_updated_by</code>.
     */
    @Column(name = "last_updated_by", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getLastUpdatedBy();

    /**
     * Getter for <code>database_usage.provenance</code>.
     */
    @Column(name = "provenance", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getProvenance();
}
