/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * entities which have specific permissions which replace the default permission
 * group
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "permission_group_entry"
)
public interface IPermissionGroupEntry extends Serializable {

    /**
     * Getter for <code>permission_group_entry.entity_id</code>. the id of the
     * entity being given specific permissions
     */
    @Column(name = "entity_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getEntityId();

    /**
     * Getter for <code>permission_group_entry.permission_group_id</code>.
     * identifier of the permission group being linked to
     */
    @Column(name = "permission_group_id", nullable = false)
    @NotNull
    @Nonnull
    public Long getPermissionGroupId();

    /**
     * Getter for <code>permission_group_entry.entity_kind</code>. the type of
     * the entity being given specific permissions
     */
    @Column(name = "entity_kind", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getEntityKind();
}
