/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "person"
)
public interface IPerson extends Serializable {

    /**
     * Getter for <code>person.id</code>.
     */
    @Column(name = "id")
    @Nullable
    public Long getId();

    /**
     * Getter for <code>person.employee_id</code>.
     */
    @Column(name = "employee_id", length = 128)
    @Size(max = 128)
    @Nullable
    public String getEmployeeId();

    /**
     * Getter for <code>person.display_name</code>.
     */
    @Column(name = "display_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getDisplayName();

    /**
     * Getter for <code>person.email</code>.
     */
    @Column(name = "email", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getEmail();

    /**
     * Getter for <code>person.user_principal_name</code>.
     */
    @Column(name = "user_principal_name", length = 255)
    @Size(max = 255)
    @Nullable
    public String getUserPrincipalName();

    /**
     * Getter for <code>person.department_name</code>.
     */
    @Column(name = "department_name", length = 255)
    @Size(max = 255)
    @Nullable
    public String getDepartmentName();

    /**
     * Getter for <code>person.kind</code>.
     */
    @Column(name = "kind", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getKind();

    /**
     * Getter for <code>person.manager_employee_id</code>.
     */
    @Column(name = "manager_employee_id", length = 128)
    @Size(max = 128)
    @Nullable
    public String getManagerEmployeeId();

    /**
     * Getter for <code>person.title</code>.
     */
    @Column(name = "title", length = 255)
    @Size(max = 255)
    @Nullable
    public String getTitle();

    /**
     * Getter for <code>person.office_phone</code>.
     */
    @Column(name = "office_phone", length = 128)
    @Size(max = 128)
    @Nullable
    public String getOfficePhone();

    /**
     * Getter for <code>person.mobile_phone</code>.
     */
    @Column(name = "mobile_phone", length = 128)
    @Size(max = 128)
    @Nullable
    public String getMobilePhone();

    /**
     * Getter for <code>person.organisational_unit_id</code>.
     */
    @Column(name = "organisational_unit_id")
    @Nullable
    public Long getOrganisationalUnitId();

    /**
     * Getter for <code>person.is_removed</code>.
     */
    @Column(name = "is_removed")
    @Nullable
    public Boolean getIsRemoved();
}
