/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "person_hierarchy"
)
public interface IPersonHierarchy extends Serializable {

    /**
     * Getter for <code>person_hierarchy.manager_id</code>.
     */
    @Column(name = "manager_id", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getManagerId();

    /**
     * Getter for <code>person_hierarchy.employee_id</code>.
     */
    @Column(name = "employee_id", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getEmployeeId();

    /**
     * Getter for <code>person_hierarchy.level</code>.
     */
    @Column(name = "level")
    @Nullable
    public Integer getLevel();
}
