/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "role"
)
public interface IRole extends Serializable {

    /**
     * Getter for <code>role.key</code>.
     */
    @Column(name = "key", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getKey();

    /**
     * Getter for <code>role.is_custom</code>.
     */
    @Column(name = "is_custom")
    @Nullable
    public Boolean getIsCustom();

    /**
     * Getter for <code>role.name</code>.
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getName();

    /**
     * Getter for <code>role.description</code>.
     */
    @Column(name = "description", nullable = false, length = 4000)
    @NotNull
    @Size(max = 4000)
    @Nonnull
    public String getDescription();

    /**
     * Getter for <code>role.user_selectable</code>.
     */
    @Column(name = "user_selectable")
    @Nullable
    public Boolean getUserSelectable();
}
