/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_preference"
)
public interface IUserPreference extends Serializable {

    /**
     * Getter for <code>user_preference.key</code>.
     */
    @Column(name = "key", nullable = false, length = 120)
    @NotNull
    @Size(max = 120)
    @Nonnull
    public String getKey();

    /**
     * Getter for <code>user_preference.value</code>.
     */
    @Column(name = "value", nullable = false, length = 2048)
    @NotNull
    @Size(max = 2048)
    @Nonnull
    public String getValue();

    /**
     * Getter for <code>user_preference.user_name</code>.
     */
    @Column(name = "user_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    @Nonnull
    public String getUserName();
}
