/*
 * This file is generated by jOOQ.
 */
package com.silo.backend.database.tables.interfaces;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_agent_info"
)
public interface IUserAgentInfo extends Serializable {

    /**
     * Getter for <code>user_agent_info.id</code>.
     */
    @Column(name = "id")
    @Nullable
    public Integer getId();

    /**
     * Getter for <code>user_agent_info.user_name</code>.
     */
    @Column(name = "user_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getUserName();

    /**
     * Getter for <code>user_agent_info.user_agent</code>.
     */
    @Column(name = "user_agent", nullable = false, length = 500)
    @NotNull
    @Size(max = 500)
    @Nonnull
    public String getUserAgent();

    /**
     * Getter for <code>user_agent_info.resolution</code>.
     */
    @Column(name = "resolution", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getResolution();

    /**
     * Getter for <code>user_agent_info.operating_system</code>.
     */
    @Column(name = "operating_system", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getOperatingSystem();

    /**
     * Getter for <code>user_agent_info.ip_address</code>.
     */
    @Column(name = "ip_address", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    @Nonnull
    public String getIpAddress();

    /**
     * Getter for <code>user_agent_info.login_timestamp</code>.
     */
    @Column(name = "login_timestamp", nullable = false, precision = 6)
    @NotNull
    @Nonnull
    public Timestamp getLoginTimestamp();
}
